src/pages/MyPage.tsx
스타일컴퍼넌트를 사용해 마이페이지 UI를 업데이트합니다
by 김남규
- mypage ui update
- ui/mypage -> dev
- mypage ui update
#ui/mypage
=> ui(MyPage): update mypage style

src/pages/Detail.tsx
스타일컴퍼넌트를 사용해 디테일페이지 UI를 만듭니다.
by 김남규
- detail page style update
- ui/detail -> dev
- detail page UI update
#ui/detail
=> ui(Detail): update detail style

db.json, src/pages/CategoryPage.tsx, src/pages/CategoryPageDetail.tsx, src/pages/Home.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/pages/WritePage.tsx, src/router/Router.tsx, src/types.d.ts
- 각 카테고리를 누르면 해당하는 카테고리의 Data를 받아오고 글을 누르면 해당하는 글의 조회수가 1씩 증가합니다.
- feat/Category -> dev
- 카테고리 누르면 해당하는 카테고리의 Data를 받아옴
- 글작성 하면 Data 저장 및 Detail Page로 이동
- 글을 누르면 views(조회수)가 1씩 증가합니다.
- 각 코드마다 주석을 상세히 작성해보았습니다. 이건 각자 지워주셔도 무방합니다.
#18 
by @km-young
=> feat:Category 카테고리 home page 기능구현 완료 및 글쓰기,detail page도 test겸 간단한 코드 작성

db.json, src/components/comment/CommentInput.tsx, src/components/comment/CommentsList.tsx, src/pages/CategoryPageDetail.tsx, src/pages/Detail.tsx, src/pages/Home.tsx, src/pages/WritePage.tsx, src/types.d.ts
- 댓글 추가,삭제가 가능해집니다.
- feat/comment -> dev
- 댓글 추가 후 바로 UI 업데이트
- 댓글 삭제 후 바로 UI 업데이트
#29 
by @km-young
=> feat:comment 댓글 추가,삭제 기능을 구현했습니다.

db.json, package.json, src/components/etc/SerchInput.tsx, src/pages/CategoryPage.tsx, src/router/Router.tsx, src/types.d.ts, yarn.lock
- 검색이 가능해집니다.
- feat/search -> dev
- 제목,내용,작성자 로 검색할 수 있는 기능 구현
- 
#20 
by @km-young
=> feat:search 제목,내용,작성자 로 검색기능 구현완료

db.json, package-lock.json, src/components/layout/Header.tsx, src/pages/CategoryPage.tsx, src/pages/Detail.tsx, src/pages/SignIn.tsx, src/types.d.ts, yarn.lock
- 디테일 바로가기 신청 -> 비로그인 상태라면 로그인컴포넌트 진입 -> 로그인 진행하면 디테일 페이지로 이동, 그 외 상황은 pathname '/'로 이동하게 됩니다.
- fix/detail -> dev
- 바로신청하기 클릭 시 비로그인 상태라면 로그인페이지로 이동, 로그인 완료 시home이 아닌  이전 페이지로 돌아가게 설정했스비다.
#39 
by @km-young
=> fix:detail 

db.json, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/router/Router.tsx
- 로그인,회원가입 시 input에서 enter key로 submit이 가능해집니다.
- fix/auth -> dev
- input마다 onKeyDown 속성을 넣어서 enter key로 submit이 가능하게끔 수정하였습니다.
by @km-young
=> fix:auth input에서 Enter key로 submit 가능하게 수정

src/components/etc/SearchInput.tsx
- 모든 페이지에서 검색이 가능해집니다.
-  카테고리 페이지가 아닌 페이지에서 검색 진행 시 자동으로 전체검색 되도록 수정하였습니다.
by @km-young
=> fix:search 

src/pages/MyPage.tsx
- mypage 머지 후 코드 중복되는 부분 있어 삭제했습니다.
- fix/mypage -> dev
- mypage 머지 후 코드 중복되는 부분 있어 삭제했습니다.
by @km-young
=> fix:mypage 충돌 해결 후 코드 중복부분 삭제

src/App.tsx, src/pages/Home.tsx, src/styles/GlobalStyle.tsx
- font스타일을 이제 적용되어 사용됩니다. 
- fix : font-> dev
- font 스타일이 추가되었습니다. 
by @KoreaMoney
=> fix : font 스타일 추가 됩니다.

db.json, src/pages/Home.tsx, src/pages/MyPage.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/types.d.ts
- fix:auth 구글로그인 데이터 map돌아가는걸 함수 안에 넣었습니다.
- fix/auth -> dev
- fix:auth 구글로그인 데이터 map돌아가는걸 함수 안에 넣었습니다.
by @km-young
=> fix:auth 구글로그인 데이터 map돌아가는걸 함수 안에 넣었습니다.

db.json, src/api.tsx, src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/components/mypage/Profile.tsx, src/pages/MyPage.tsx
ui(MyPage): 마이페이지와 포인트 모달 UI를 수정합니다.
마이페이지에서 세부 컴포넌트를 나눕니다.
by kimnamgyu93
- UI변경과 유저포인트를 받아옵니다.
- ui/mypage-modal -> dev
- 마이페이지 세부컴포넌트를 나누고 UI수정, 유저포인트  GET
#12 
=> ui(MyPage): 마이페이지와 포인트 모달 UI를 수정합니다.

db.json, src/components/etc/SearchInput.tsx, src/components/layout/Header.tsx, src/pages/Home.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx
fix : 소셜 로그인 시 home화면으로 가지 않는 버그 수정
- 앞으로 auth ui 사용가능합니다.
- 앞으로 소셜 로그인 시 home화면으로 이동합니다.
- 소셜 로그인 시 home화면으로 가지 않는 버그 수정하였습니다.
- 로그인 회원가입 page code 정리 하였습니다.
- auth ui 제작되었습니다. 
by @KoreaMoney
=> ui : ui-authservice

db.json, src/components/comment/CommentInput.tsx, src/components/comment/CommentsList.tsx, src/components/mypage/Profile.tsx, src/pages/Detail.tsx, src/pages/MyPage.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/types.d.ts
- ui:detail 디테일페이지의 UI 완성
- ui/detail -> dev
- ui:detail 디테일페이지의 UI 완성
#13 
by @km-young
=> ui:detail 디테일페이지의 UI 완성

db.json, src/api.tsx, src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/components/mypage/Profile.tsx, src/pages/Detail.tsx, src/pages/MyPage.tsx
- 글 찜, 유저 좋아요 가 가능해집니다.
- feat/like -> dev
- 디테일에서 따봉 누르면 유저 좋아요, 하트 누르면 글 찜
by @km-young
=> feat:like 유저 좋아요 기능과, 글 찜 기능을 만들었습니다.

.env, .gitignore, src/api.tsx, src/components/comment/CommentInput.tsx, src/components/comment/CommentsList.tsx, src/components/mypage/PointModal.tsx, src/components/mypage/Profile.tsx, src/pages/CategoryPage.tsx, src/pages/Detail.tsx, src/pages/EditPage.tsx, src/pages/Home.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/pages/Transaction.tsx, src/pages/WritePage.tsx
by kimnamgyu93
- 로컬이나 서버 둘 다 작업할 수 있게 env 설정합니다
- fix/env -> dev
- env에서 주소설정으로 로컬이나 서버에서 api작업을 할 수 있습니다.
#7 
=> fix(env): env설정하여 로컬에서도 작업할 수 있게 합니다

db.json, src/api.tsx, src/components/auth/FindPW.tsx, src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/components/mypage/Profile.tsx, src/pages/Detail.tsx, src/pages/MyPage.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/pages/Transaction.tsx
- fix:mypage 충돌수정
- fix/mypage-> dev
- fix:mypage 충돌수정
by @km-young
=> fix:mypage 충돌수정

src/pages/EditPage.tsx, src/pages/WritePage.tsx, yarn.lock
글쓰기페이지, 수정페이지 ui가 변경됐습니다.
- feat/write -> dev
writePage, editPage UI 구현
#이슈이름
by @Um-Junsik
=> ui: writepage, editpage ui 변경

src/components/mypage/PointModal.tsx, src/pages/CategoryPage.tsx, src/pages/Detail.tsx, src/pages/EditPage.tsx, src/pages/Home.tsx, src/pages/MyPage.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/pages/Transaction.tsx, src/pages/WritePage.tsx, src/types.d.ts
- etc 거래로직 수정
- feat/etc-> dev
- etc 거래로직 수정, 아직 더 수정해야합ㄴ다.
by @km-young
=> feat:etc 거래로직 수정

src/components/mypage/PointModal.tsx, src/pages/Detail.tsx, src/pages/Transaction.tsx, src/types.d.ts
- 결제 취소,완료 되어도 더이상 포인트가 null이나 NaN이 되지 않습니다.
- 포인트가 부족하면 알림이 뜨며 신청하지 못합니다.
- fix/transfer-> dev
- Detail 컴포넌트에서 결제로직을 수정하였습니다.
by @km-young
=> 결제로직 1차 마무리

src/atom.ts, src/components/auth/FindPW.tsx, src/components/comment/CommentInput.tsx, src/components/comment/CommentsList.tsx, src/components/etc/SearchInput.tsx, src/components/layout/Footer.tsx, src/components/layout/Header.tsx, src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/components/mypage/Profile.tsx, src/index.tsx, src/pages/CategoryPage.tsx, src/pages/Detail.tsx, src/pages/EditPage.tsx, src/pages/Home.tsx, src/pages/MyPage.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/pages/Transaction.tsx, src/pages/WritePage.tsx, src/router/Router.tsx, src/styles/styledComponent/auth.ts, src/styles/styledComponent/category.ts, src/styles/styledComponent/detail.ts, src/styles/styledComponent/editPage.ts, src/styles/styledComponent/home.ts, src/styles/styledComponent/myPage.ts, src/styles/styledComponent/transaction.ts, src/styles/styledComponent/writeEdit.ts
- fix : clean-coding진행 (성능 58에서 66으로 성장)시켰습니다.
- fix : clean-coding> dev
- clean-coding진행 ( 불필요한 코드와 반복성 코드 단일)
by @KoreaMoney
=> fix : clean-coding진행 (성능 58에서 66으로 성장)

src/api.ts, src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/pages/MyPage.tsx
- api 오류 수정, 유저 연락가능시간을 나타냅니다.
- feat/mypage -> dev
- api 오류 수정, 유저 연락가능시간을 나타냅니다.
#14 
=> Feat/mypage: api 오류 수정, 유저 연락가능시간을 나타냅니다.

src/components/mypage/PointHistoryList.tsx, src/pages/MyPage.tsx
- PointHistory에 날짜, Title, Price를 출력합니다.
유저이용가능시간을 수정,출력 합니다.
- feat/profile -> dev
- PointHistory에 날짜, Title, Price를 출력합니다.
유저이용가능시간을 수정,출력 합니다.
#14 
=> feat(MyPage): Profile의 기능을 만듭니다.

src/components/mypage/Chart.tsx, src/pages/MyPage.tsx
- 앞으로 기간 별로 조회수 확인이 가능합니다. 
-fix /chart  -> dev
-  기간 별로 조회수 확인이 가능하게 만들었습니다. 
by @KoreaMoney
=> fix : chart 기간별 분류 진행

src/components/detail/SellerInfo.tsx, src/components/mypage/Chart.tsx, src/pages/Detail.tsx, src/pages/WritePage.tsx, src/styles/styledComponent/detail.ts
- 앞으로 판매자 정보를 따로 분리되어 사용이 가능합니다. ui적으로는 작업이 되지 않았습니다. 
- feat/detail-change -> dev
- 판매자 정보를 따로 분리했습니다. 
by @KoreaMoney
=> feat : 판매자 정보 따로 분리

src/api.ts, src/components/mypage/PointHistoryList.tsx, src/pages/MyPage.tsx
- 마이페이지의 관심목록, 판매내역, 구매내역, 후기관리 리스트를 출력합니다.
- feat/mypagelist -> dev
- onSalePosts, comments, posts를 GET하고 조건에 맞는 List를 출력합니다.
#14 
=> feat(MyPage): 마이페이지 관심목록과 판매,구매 내역과 후기관리를 나타냅니다.

src/api.ts, src/components/comment/CommentInput.tsx, src/components/comment/CommentsList.tsx, src/pages/Detail.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/pages/Transaction.tsx, src/types.d.ts
- 댓글 작성 시 판매자의 commentsCount가 1씩 증가합니다.
- 댓글 삭제 시 판매자의 commentsCount가 1씩 감소합니다.
- comments, users, posts DB구조가 변경됩니다.
- transaction page에서 거래완료 시 거래완료 시간이 데이터에 저장됩니다. 
- transaction page에서 거래취소 시 거래취소 시간이 데이터에 저장됩니다.
- fix/comments,transaction -> dev
- 댓글 작성 시 판매자의 commentsCount +1씩 되도록 수정
- comment, users, posts DB구조 노션대로 수정
- transaction page에서 거래 완료 및 취소 시 거래완료된 시간, 취소된 시간 데이터로 추가될 수 있도록 수정
#63
by @km-young
=> fix:comments,transaction

src/api.ts, src/components/mypage/Profile.tsx, src/components/mypage/UserTime.tsx, src/pages/MyPage.tsx
- 마이페이지의 기능 일부를 컴퍼넌트화 합니다.
- feat/mypageComponents -> dev
- components폴더의 mypage폴더에 UserTime파일을 생성해서 관리합니다.
#14 
=> feat(MyPage): 마이페이지 일부 기능을 컴퍼넌트화 합니다.

src/components/auth/FindPW.tsx, src/components/comment/CommentInput.tsx, src/components/comment/CommentsList.tsx, src/components/layout/Footer.tsx, src/components/layout/Header.tsx, src/components/mypage/Profile.tsx
- 앞으로 수정된 테마를 사용이 가능합니다. 
- fix : theme-> dev
- 버그 수정
by @KoreaMoney
=> fix : theme

src/atom.ts, src/pages/Detail.tsx, src/pages/Transaction.tsx
- 거래 취소 시 구매자에게 환불이 됩니다.
- 거래 취소 시 ui에 바로 업데이트 됩니다.
- 거래 취소 시 거래 완료 안되게 됩니다.
- 거래 완료 시 ui에 바로 업데이트 됩니다.
- 거래 완료 시 거래 취소 안되게 됩니다.
- fix/transaction -> dev
--트랜젝션 페이지
-거래 취소 시 구매자에게 환불 안되던 버그 수정
-거래 완료 시 ui 바로 업데이트 안되던 버그 수정
-거래 취소 시 ui 바로 업데이트 안되던 버그 수정
-거래 완료 시 거래 취소 안되게 수정
-거래 취소 시 거래 완료 안되게 수정
--디테일 페이지
-디테일페이지 접속 시 isCancle,isDone RecoilState false로 초기화
by @km-young
=> fix:transaction

public/index.html, src/components/modal/CustomModal.tsx, src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/components/mypage/ProfileImg.tsx, src/components/mypage/UserName.tsx, src/components/mypage/UserTime.tsx, src/pages/MyPage.tsx, src/styles/styledComponent/myPage.ts
- 닉네임을 클릭하면 수정가능합니다.
- 닉네임을 최대 8자로 제한합니다.
- 커스텀 모달에 theme을 적용합니다.
- 마이페이지의 UI를 수정합니다. (진행중)
- ui/mypage -> dev
- 닉네임을 클릭하면 input창을 토글합니다. 
- 커스텀 모달의 폰트 사이즈와 색상을 theme에 맞게 변경합니다.
- 마이페이지의 찜 목록, 판매 내역, 구매 내역, 후기에 grid를 적용합니다.
- pointmodal의 ui를 theme에 맞게 수정합니다.
#12 
=> ui(MyPage): 마이페이지의 UI를 수정합니다.

src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/components/mypage/ProfileImg.tsx, src/components/mypage/UserTime.tsx, src/pages/MyPage.tsx, src/styles/styledComponent/myPage.ts
- 프로필에 관련된 UI를 전체 수정합니다.
- ui/profile -> dev
- MyPage, PointModal, PointHistoryList, UserName, UserTime, ProfileImg 파일의 UI를 수정합니다.
#12 
=> ui(Profile): Profile 관련 UI를 수정합니다.

public/index.html, src/components/mypage/PointHistoryList.tsx, src/components/mypage/UserTime.tsx, src/pages/MyPage.tsx, src/styles/styledComponent/myPage.ts
- 마이페이지, 프로필페이지의 Nav UI를 수정합니다.
- 유저 이용 가능 시간이 없을 때 문구를 띄워줍니다.
- ui/MypageProfile -> dev
- 마이페이지, 프로필페이지의 Nav UI를 컨셉에 맞게 변경합니다.
- 유저 이용 가능 시간이 없을 때 삼항연산자를 사용하여 문구를 띄웁니다.
- index.html에 폰트 적용을 위한 Link 부분의 따옴표 오타를 수정합니다.
#12 
=> ui(MyPage): 마이페이지 Nav UI와 Profile Nav UI를 수정합니다.

src/components/mypage/PointModal.tsx, src/components/mypage/ProfileImg.tsx, src/pages/MyPage.tsx, src/styles/styledComponent/myPage.ts
- 회원관리 UI를 수정합니다.
- ui/mypageinfo -> dev
- 회원관리 UI를 수정합니다.
#12 
=> ui(MyPage): 회원관리 UI를 수정합니다.

src/components/categoryHome/Post.tsx, src/pages/Detail.tsx, src/pages/Home.tsx, src/pages/MyPage.tsx, src/pages/Transaction.tsx, src/styles/styledComponent/myPage.ts
- Text '원'을 'P'로 수정합니다.
- Post에 호버기능이 추가됩니다.
- ui/newmypage -> dev
- Text '원'을 'P'로 수정합니다.
- Post에 호버기능이 추가됩니다.
#80 
=> fix(UIText): UI와 text를 변경합니다.

src/components/error/Error404.tsx, src/components/error/index.tsx, src/components/layout/Header.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/router/Router.tsx, src/styles/styledComponent/auth.ts
- 앞으로 로그인 회원가입 ui를 사용할 수 있습니다. 
- ui : auth-ui -> dev
- 회원가입 ui적용
#37 
by @KoreaMoney
=> ui : auth-ui를 작업이 되었습니다.

src/components/auth/FindPW.tsx, src/components/error/Error404.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/types.d.ts
- 앞으로 404페이지가 적용됩니다.
- find-pw사용이 가능합니다. 
- ui : 404error, find pw -> dev
- 404페이지제작,
- find-pw제작
by @KoreaMoney
=> ui : 404error, find pw

src/components/error/Error404.tsx, src/components/mypage/member/MemberInfo.tsx, src/pages/Detail.tsx, src/pages/Home.tsx, src/pages/MyPage.tsx, src/pages/Transaction.tsx, src/styles/styledComponent/detail.ts
- 앞으로 일부 알럿창이 추가 되어 사용이 가능합니다.  
- feat/ui-feature-add-> dev
- 일부 알럿창이 추가 되었습니다.
by @KoreaMoney
=> feat  : 일부 알럿창이 추가 되었습니다.

src/components/home/Banner.tsx
- 앞으로 배너이미지와 버그 수정으로 정상적으로 사용이 가능합니다. 
- hotfix : banner -> dev
- 배너 이미지와 링크 버그 수정
by @KoreaMoney
=> hotfix : banner

src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/pages/MyPage.tsx, src/styles/styledComponent/myPage.ts
- 마이페이지의 관심, 판매, 구매 목록에서 Post를 클릭하면 해당 페이지로 이동합니다.
- feat/mypagelist -> dev
- 마이페이지에서 Post의 Img를 onClick하면 navigate를 통해 해당 페이지로 이동합니다.
- 마이페이지에서 Post의 마우스 커서를 포인터로 변경합니다.
#14 
=> feat(Mypage): 마이페이지에서 Post를 클릭하면 해당 페이지로 이동합니다.

src/pages/ReviewPage.tsx
후기 댓글 작성이 원활하게 작동합니다
- fix/badge명 -> dev
후기 페이지 예외처리에 거래가 isDone이 false일때 접근 못하게 추가
댓글을 작성했음에도 ''으로 내용이 들어가던 현상 수정
#이슈이름
by @Um-Junsik
=>  fix: 후기 댓글이 제대로 나오지 않던 현상 수정

src/pages/Detail.tsx, src/pages/Transaction.tsx, src/types.d.ts
- onsaleposts 데이터에 buyernickname추가
#80 
by @km-young
=> onsaleposts 데이터에 buyernickname추가

src/atom.ts, src/components/modal/CustomModal.tsx, src/components/modal/Custom사용법.txt, src/components/transaction/BuyerModal.tsx, src/pages/Detail.tsx, src/styles/GlobalStyle.tsx
- 디테일페이지에서 판매자가 구매자 명단확인 및 onsalepost로 갈 수 있는 모달 완성
- feat,ui/onSaleModal -> dev
- 디테일페이지에서 판매자가 구매자 명단확인 및 onsalepost로 갈 수 있는 모달 완성
by @km-young
=> feat,ui/onSaleModal: 디테일페이지에서 판매자가 구매자 명단확인 및 onsalepost로 갈 수 있는 모달 완성

src/api.ts, src/components/detail/BuyerInfo.tsx, src/pages/Detail.tsx, src/pages/Transaction.tsx
- 트랜잭션 페이지에서 판매자라면 구매자 프로필이, 구매자라면 판매자 프로필이 보이도록 수정했습니다.
- fix/memberInfo -> dev
#80 
by @km-young
=> fix/memberInfo: 트랜잭션 페이지에서 판매자라면 구매자 프로필이, 구매자라면 판매자 프로필이 보이도록 수정했습니다.

src/components/error/Error404.tsx, src/components/etc/MoveTop.tsx, src/components/home/Banner.tsx, src/components/layout/Footer.tsx, src/components/layout/Layout.tsx, src/components/mypage/member/UserName.tsx, src/pages/Home.tsx, src/pages/Transaction.tsx
- 앞으로 고정된 홈 ui를 사용이 가능합니다. 
- Fix/home UI size -> dev
- 홈 ui, 올라가기 기능, 배너 전체 교환
#22 
by @KoreaMoney
=> Fix/home UI size

src/components/mypage/PointHistoryList.tsx
- 포인트내역이 입, 출금이 반대로 표시되던 현상을 수정합니다.
- feat/mypage -> dev
- 적용중이던 텍스트를 반대로 변경합니다.
#127 
=> fix(mypage): 포인트내역이 입, 출금이 반대로 표시되던 현상을 수정합니다.

src/atom.ts, src/components/detail/BuyerInfo.tsx, src/components/detail/SellerInfo.tsx, src/components/modal/BuyerModal.tsx, src/components/modal/CustomModal.tsx, src/components/modal/Custom사용법.txt, src/components/modal/KakaoModal.tsx, src/components/mypage/member/MemberInfo.tsx, src/pages/Detail.tsx, src/pages/SignIn.tsx, src/pages/Transaction.tsx
-판매자프로필에만 카카오문의하기 버튼을 보이게 하였습니다.
-카카오로 문의하기 버튼 클릭 시 카카오ID가 있는 모달이 보여집니다.
-커스텀모달에 overflow 커스텀 가능하게 수정
-멤버프로필에 배지개수 나오게 수정
- uI,feat/kakaomodal-> dev
by @km-young
=> UI,feat/kakaomodal

src/pages/MyPage.tsx
- 리스트가 중복해서 뜨던 현상을 수정합니다.
- feat/mypageselllist -> dev
- onsaleposts가 아닌 post를 받아옵니다.
#fix:mypage
=> fix(mypage): 리스트가 중복해서 뜨던 현상을 수정합니다.

src/pages/MyPage.tsx, src/pages/Transaction.tsx
회원탈퇴 시 글리치에서도 유저정보 삭제되게 변경
-fix/mypage-> dev
by @km-young
=> fix/mypage:회원탈퇴 시 글리치에서도 유저정보 삭제되게 변경

src/components/modal/BuyerModal.tsx
by kimnamgyu93
- 모달창 종료버튼을 생성합니다.
- ui/buyermodal -> dev
- 모달창 종료버튼을 생성합니다.
=> ui(buyermodal): 모달창 종료버튼을 생성합니다.

src/components/mypage/PointHistoryList.tsx, src/components/mypage/PointModal.tsx, src/pages/Detail.tsx, src/pages/SignIn.tsx, src/pages/Transaction.tsx, src/pages/WritePage.tsx
- hotfix되었습니다. 
- hotfix : dev-> dev
- 현재 작업 된 기능을 설명해주세요
by @KoreaMoney
=> hotfix : dev수정

src/components/mypage/member/ProfileImg.tsx, src/pages/WritePage.tsx
- 사진 올리고 삭제 후 파일선택 창에서 닫기를 누르면 콘솔 에러나던부분 수정
- fix/writePage -> dev
by @km-young
=> fix/writePage: 사진 올리고 삭제 후 파일선택 창에서 닫기를 누르면 콘솔 에러나던부분 수정

src/api.ts, src/pages/MyPage.tsx
- 찜 목록을 보여줍니다.
- fix/mypage -> dev
- 현재 작업 된 기능을 설명해주세요
#155 
=> fix(mypage): 찜 목록을 보여줍니다.

src/pages/MyPage.tsx
- 앞으로 회원탈퇴 오류는 방지가 됩니다. 
- hotfix/system -> dev
-  회원탈퇴 오류 버그 해결 했습니다. 
by @KoreaMoney
=> hotfix : 회원탈퇴

src/components/error/ErrorETC.tsx, src/components/modal/CustomModal.tsx, src/styles/styledComponent/home.ts
- 앞으로 모달 버그없이 사용이 가능합니다.
- fix/user-feedback4 -> dev
- 모달 버그를 수정했습니다. 
by @KoreaMoney
=> fix : 모달 크기 버그 수정, a태그 삭제 후 변경

src/components/mypage/member/Badge.tsx, src/components/mypage/member/ProfileImg.tsx
- 배지에 마우스 오버 시 확대합니다.
- 잠금 배지 클릭 시 오픈 조건을 알럿을 통해 알려줍니다.
- feat/badge -> dev
- 잠김 상태만 따로 빼서 새로운 스타일드 컴퍼넌트에 적용 후, if문을 없애고 삼항연산자로 대체합니다.
#175
=> feat(Badge): '회원정보 변경'의 배지 로직에 의한 UI를 수정합니다.

src/components/comment/CommentsList.tsx, src/components/detail/PostImg.tsx, src/components/detail/PostInfo/PostInfo.tsx, src/components/detail/SellerInfo.tsx, src/components/detail/content/DetailContent.tsx
- 더이상 에러가 발생하지 않습니다.
- Fix/detail,transaction -> dev
- 머지 후 에러 수정
#171 
by @km-young
=> fix/detail,transaction: 머지 후 에러 수정

src/api.ts, src/components/mypage/PointHistoryList.tsx, src/components/mypage/member/ProfileImg.tsx, src/pages/MyPage.tsx
- 프로필 사진 수정 시 프리뷰 합니다.
- 포인트 내역 히스토리가 최신순으로 나타납니다.
- fix/profile -> dev
- 프로필 사진 수정 시 프리뷰 합니다.
- 포인트 내역 히스토리가 최신순으로 나타납니다.
#46 
=> fix(mypage): 마이페이지의 기능을 수정합니다.

src/api.ts, src/atom.ts, src/components/modal/BuyerModal.tsx, src/components/modal/CustomModal.tsx, src/components/mypage/Chart.tsx, src/components/mypage/PointHistoryList.tsx, src/pages/Detail.tsx, src/pages/MyPage.tsx, src/pages/SignIn.tsx
- 앞으로 포인트 내역 차트를 사용할 수 있습니다. 
- feat : chart point -> dev
- 포인트 내역 차트를 구성햇습니다. 
#177 
by @KoreaMoney
=> feat : chart point내역으로 추가합니다.

package.json, src/atom.ts, src/components/detail/SellerInfo.tsx, src/pages/Detail.tsx, src/pages/EditPage.tsx, src/pages/WritePage.tsx
앞으로 글작성,수정시 압축된 이미지를 사용하실수 있습니다
- Feat/image compress 명 -> dev
글 작성,글 수정시 이미지 압축 라이브러리를 통해 효율을 개선시켰습니다.
#177 
by @Um-Junsik
=> feat: 글작성,수정시 이미지 압축 구현

src/components/detail/PostImg.tsx, src/components/modal/KakaoModal.tsx
- 앞으로 상세페이지 내 이미지 클릭 시 모달로 이미지 100% 띄우기 가능합니다. 
- feat/userFeed-back -> dev
- 상세페이지 내 이미지 클릭 시 모달로 이미지 100% 띄우기
#177 
by @KoreaMoney
=> feat : 상세페이지 내 이미지 클릭 시 모달로 이미지 100% 띄우기

src/components/modal/KakaoModal.tsx, src/types.d.ts
1:1 채팅에서 이미지를 보낼수 있습니다
Feat/chatimage -> dev
채팅에서 이미지파일을 전송해서 보여주는 기능 구현
#177 
by @Um-Junsik
=> feat:채팅내에서 이미지를 보내는 기능 추가

src/atom.ts, src/components/detail/PostInfo/PostInfo.tsx, src/components/modal/BuyerModal.tsx
- fix/buyermodal -> dev
- 디테일의 구매자명단에 해당 포스트에 해당하는 온세일포스트만 나오게 하였습니다.
#177 
by @km-young
=> fix/buyermodal: 

src/components/modal/BuyerModal.tsx, src/components/modal/KakaoModal.tsx
채팅창에서 사진을 크게 볼 수 있습니다.
Fix/chatimg-> dev
채팅창의 이미지를 클릭시 새로운 페이지에서 큰 사이즈로 볼 수 있습니다.
#177 
by @Um-Junsik
=> fix:채팅창에서 이미지 클릭시 크게 볼수있게 수정

src/atom.ts, src/components/detail/PostInfo/PostInfo.tsx, src/components/modal/BuyerModal.tsx, src/pages/MyPage.tsx, src/pages/UserProfile.tsx
- detail post의 거래완료 진행 시 매칭중 글이 있을 경우 거래완료 되지 않게 수정되었습니다.
- fix/detail-> dev
- 거래중인 글이 없어야지만 디테일 포스트 거래완료 진행되게 예외처리 하였습니다.
#177 
by @km-young
=> fix/detail: 

src/atom.ts, src/components/detail/PostInfo/PostInfo.tsx, src/components/modal/BuyerModal.tsx, src/components/modal/KakaoModal.tsx, src/pages/Detail.tsx, src/pages/MyPage.tsx, src/pages/WritePage.tsx
- fix/etc -> dev
-자잘한 에러 수정
#177 
by @km-young
=> fix/etc: 자잘한 에러 수정

src/api.ts, src/components/etc/Inquire.tsx, src/components/etc/inquire/AddForm.tsx, src/components/etc/inquire/InquireList.tsx, src/components/etc/inquire/InquirePost.tsx
by kimnamgyu93
- 고객 문의하기 기능을 만듭니다.
- feat/mypage -> dev
- 고객 문의하기 CRUD를 만듭니다.
#196
=> feat(mypage): 고객 문의하기 기능을 만듭니다.

src/components/layout/Header.tsx
- 판매중 Post 수를 나타냅니다.
- feat/header -> dev
- 판매중 Post 수를 나타내기위해 onsalePosts의 sellerUid 중 isDone이 false인 것만 받아옵니다.
#197
=> feat(header): 판매중 Post 수를 나타냅니다.

src/atom.ts, src/components/mypage/PointHistoryList.tsx, src/components/mypage/member/MemberInfo.tsx, src/components/mypage/member/UserName.tsx, src/pages/MyPage.tsx, src/styles/styledComponent/myPage.ts
- 포인트내역에 상대 닉네임이 보입니다.
- 닉네임 중복검사를 합니다.
- fix/mypage -> dev
- 포인트내역에 상대 닉네임이 보입니다.
- 닉네임 중복검사를 합니다.
#204
=> fix(mypage):포인트내역에 상대 닉네임이 보입니다. 닉네임 중복 검사 로직을 수정합니다.

src/components/mypage/member/MemberInfo.tsx, src/components/mypage/member/UserName.tsx
- 닉네임 중복검사 로직을 심화 합니다.
- fix/UserName-> dev
- 닉네임 중복검사 로직을 심화 합니다.
#205
=> fix(UserName): 닉네임 중복검사 로직을 심화 합니다.

public/index.html
What is this PR? 🔍
seo를 위해 검색어 최적화작업 진행
branch
feat/seo_1 -> main
Changes 📝
seo를 위해 검색어 최적화작업 진행
by @KoreaMoney
=> hotfix : seo 검색어 등록

src/pages/WritePage.tsx
- 앞으로 글쓰기 페이지의 로딩이 적용됩니다. 
- hotfix/wirtepage-loading -> dev
-  글쓰기 페이지의 로딩 수정하였습니다. 
#160 
by @KoreaMoney
=> hotfix : 글쓰기 페이지 로딩 loading

src/api.ts
- 앞으로 거래취소도 실시간 반영이 됩니다. 
- hotfix/bug_2 > dev
- api iscancel추가
by @KoreaMoney
=> hotfix : 거래 취소 버그 수정

src/components/detail/SellerInfo.tsx, src/pages/Home.tsx
- 앞으로 home data 에러해결되어 사용이 가능합니다. 
- hotfix : home data -> main
-  home data 에러 수정 ( 핫한 이음이들)
#160 
by @KoreaMoney
=> hotfix : home data 에러

src/components/layout/Header.tsx, src/components/transaction/PostInfo/PostInfo.tsx
- 앞으로 header와 구매완료 시 confirm으로 변경되어 사용됩니다.
- hotfix > main
- header와 구매완료 시 confirm으로 변경
by @KoreaMoney
=> hotfix : header와 구매완료 시 confirm으로 변경

src/components/layout/Header.tsx, src/pages/Transaction.tsx
=> hotfix : 용어 변경

src/components/layout/Header.tsx, src/components/modal/BuyerModal.tsx, src/components/modal/HeaderbuyerModal.tsx, src/components/transaction/OnSalePostImg .tsx, src/pages/Transaction.tsx
- 앞으로 무한랜더링 버그 수정
- hotfix : bug  -> main
- 앞으로 무한랜더링 버그 수정 되었습니다. 
#215 
by @KoreaMoney
=> hotfix : bug 에러 수정

src/pages/MyPage.tsx
- 앞으로 탈퇴 bug수정이 되어 사용 가능합니다. 
- hotfix/bug-9-> main
- 탈퇴 bug수정 하였습니다. 
by @KoreaMoney
=> hotfix :  탈퇴 bug수정

src/pages/Transaction.tsx
- 앞으로 DEV에서 기능할 내용을 적어주세요
- 현재 작업 된 기능을 설명해주세요
#이슈이름
by @유저이름
=> hotfix : loader추가하기

src/components/mypage/PointModal.tsx, src/components/mypage/member/MemberInfo.tsx, src/pages/EditPage.tsx, src/pages/MyPage.tsx, src/pages/UserProfile.tsx, src/pages/WritePage.tsx
- 앞으로 DEV에서 기능할 내용을 적어주세요
- 현재 작업 된 기능을 설명해주세요
#이슈이름
by @유저이름
=> hotfix : fix

package.json, src/App.tsx, src/index.tsx
- 앞으로 리액트 핼멧으로 seo를 지원합니다. 
-feat : seoSetup -> main
- 리액트 핼멧 셋업했습니다.
by @KoreaMoney
=> feat : seo세팅
